### ISSUE TITLE
two errors to report

### ISSUE THREAD

**Issue by persianphilosopher** [jupitern/slim3-skeleton#5]
I ran into two errors on a fresh install and reinstall. Each time I get the following:

```
Type: ErrorException
Code: 2
Message: session_start(): open(/var/www/skeleton/storage/sessions//sess_0sle4k0p8u692nmr122oijm481, O_RDWR) failed: No such file or directory (2)
File: /var/www/skel/app/Middleware/Session.php
Line: 27
```
The storage has a chmod 777 so I am not sure what to do.

Looking into the storage folder and the logs, it pointed out that [what appears to be a typo ](https://github.com/jupitern/slim3-skeleton/blob/0ee62c0ce07bd1209c3bc546feb8d7c2cbfd1892/config/app.php#L17)(I think) with an extra period after views. 

```
			'mail' 	=> RESOURCES_PATH."views.".DS."mail",
```

I am not sure how I could get the install process wrong and would appreciate any suggestions.

**Comment by jupitern** [comment]
Hi,
The session folder was not being created. I added the code to:
https://github.com/jupitern/slim3-skeleton/blob/master/app/Middleware/Session.php

Dont forget to give 0777 permissions to storage folder.

The typo was corrected in a previous release.
